//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    
    public partial class Orden
    {
        public Orden()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int PkOrden { get; set; }
        public int Mesa { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<double> Total { get; set; }
        
        //[XmlIgnore]
        //[IgnoreDataMember]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int PkPedido { get; set; }
        public int Platillo { get; set; }
        public int Orden { get; set; }
    
        public virtual Orden Orden1 { get; set; }
        public virtual Platillo Platillo1 { get; set; }
    }
}
namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platillo
    {
        public Platillo()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int PkPlatillo { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
