//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloOrden", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ModeloOrden : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PkOrdenField;
        
        private int MesaField;
        
        private System.DateTime FechaField;
        
        private System.Nullable<double> TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PkOrden {
            get {
                return this.PkOrdenField;
            }
            set {
                if ((this.PkOrdenField.Equals(value) != true)) {
                    this.PkOrdenField = value;
                    this.RaisePropertyChanged("PkOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Mesa {
            get {
                return this.MesaField;
            }
            set {
                if ((this.MesaField.Equals(value) != true)) {
                    this.MesaField = value;
                    this.RaisePropertyChanged("Mesa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloPlatillo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ModeloPlatillo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PkPlatilloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PkPlatillo {
            get {
                return this.PkPlatilloField;
            }
            set {
                if ((this.PkPlatilloField.Equals(value) != true)) {
                    this.PkPlatilloField = value;
                    this.RaisePropertyChanged("PkPlatillo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloPedido", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ModeloPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PkPedidoField;
        
        private int PlatilloField;
        
        private int OrdenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PkPedido {
            get {
                return this.PkPedidoField;
            }
            set {
                if ((this.PkPedidoField.Equals(value) != true)) {
                    this.PkPedidoField = value;
                    this.RaisePropertyChanged("PkPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Platillo {
            get {
                return this.PlatilloField;
            }
            set {
                if ((this.PlatilloField.Equals(value) != true)) {
                    this.PlatilloField = value;
                    this.RaisePropertyChanged("Platillo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearOrden", ReplyAction="*")]
        void CrearOrden(int Mesa, System.DateTime Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearOrden", ReplyAction="*")]
        System.Threading.Tasks.Task CrearOrdenAsync(int Mesa, System.DateTime Fecha);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverTablaOrdenResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTablaOrden", ReplyAction="*")]
        Vistas.ServiceReference1.DevolverTablaOrdenResponse DevolverTablaOrden(Vistas.ServiceReference1.DevolverTablaOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTablaOrden", ReplyAction="*")]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaOrdenResponse> DevolverTablaOrdenAsync(Vistas.ServiceReference1.DevolverTablaOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarOrden", ReplyAction="*")]
        void ModificarOrden(int PkOrden, int Mesa, System.DateTime Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarOrden", ReplyAction="*")]
        System.Threading.Tasks.Task ModificarOrdenAsync(int PkOrden, int Mesa, System.DateTime Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarOrden", ReplyAction="*")]
        void BorrarOrden(int PkOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarOrden", ReplyAction="*")]
        System.Threading.Tasks.Task BorrarOrdenAsync(int PkOrden);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearPlatillo", ReplyAction="*")]
        Vistas.ServiceReference1.CrearPlatilloResponse CrearPlatillo(Vistas.ServiceReference1.CrearPlatilloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearPlatillo", ReplyAction="*")]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.CrearPlatilloResponse> CrearPlatilloAsync(Vistas.ServiceReference1.CrearPlatilloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverTablaPlatilloResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTablaPlatillo", ReplyAction="*")]
        Vistas.ServiceReference1.DevolverTablaPlatilloResponse DevolverTablaPlatillo(Vistas.ServiceReference1.DevolverTablaPlatilloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTablaPlatillo", ReplyAction="*")]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaPlatilloResponse> DevolverTablaPlatilloAsync(Vistas.ServiceReference1.DevolverTablaPlatilloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPlatillo", ReplyAction="*")]
        Vistas.ServiceReference1.ModificarPlatilloResponse ModificarPlatillo(Vistas.ServiceReference1.ModificarPlatilloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPlatillo", ReplyAction="*")]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.ModificarPlatilloResponse> ModificarPlatilloAsync(Vistas.ServiceReference1.ModificarPlatilloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarPlatillo", ReplyAction="*")]
        void BorrarPlatillo(int PkPlatillo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarPlatillo", ReplyAction="*")]
        System.Threading.Tasks.Task BorrarPlatilloAsync(int PkPlatillo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearPedido", ReplyAction="*")]
        void CrearPedido(int Platillo, int Orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearPedido", ReplyAction="*")]
        System.Threading.Tasks.Task CrearPedidoAsync(int Platillo, int Orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPedido", ReplyAction="*")]
        void ModificarPedido(int PkPedido, int Platillo, int Orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPedido", ReplyAction="*")]
        System.Threading.Tasks.Task ModificarPedidoAsync(int PkPedido, int Platillo, int Orden);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverTablaPedidoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTablaPedido", ReplyAction="*")]
        Vistas.ServiceReference1.DevolverTablaPedidoResponse DevolverTablaPedido(Vistas.ServiceReference1.DevolverTablaPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTablaPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaPedidoResponse> DevolverTablaPedidoAsync(Vistas.ServiceReference1.DevolverTablaPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarPedido", ReplyAction="*")]
        void BorrarPedido(int PkPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarPedido", ReplyAction="*")]
        System.Threading.Tasks.Task BorrarPedidoAsync(int PkPedido);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTablaOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTablaOrden", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.DevolverTablaOrdenRequestBody Body;
        
        public DevolverTablaOrdenRequest() {
        }
        
        public DevolverTablaOrdenRequest(Vistas.ServiceReference1.DevolverTablaOrdenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverTablaOrdenRequestBody {
        
        public DevolverTablaOrdenRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTablaOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTablaOrdenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.DevolverTablaOrdenResponseBody Body;
        
        public DevolverTablaOrdenResponse() {
        }
        
        public DevolverTablaOrdenResponse(Vistas.ServiceReference1.DevolverTablaOrdenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverTablaOrdenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vistas.ServiceReference1.ModeloOrden[] DevolverTablaOrdenResult;
        
        public DevolverTablaOrdenResponseBody() {
        }
        
        public DevolverTablaOrdenResponseBody(Vistas.ServiceReference1.ModeloOrden[] DevolverTablaOrdenResult) {
            this.DevolverTablaOrdenResult = DevolverTablaOrdenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearPlatilloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearPlatillo", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.CrearPlatilloRequestBody Body;
        
        public CrearPlatilloRequest() {
        }
        
        public CrearPlatilloRequest(Vistas.ServiceReference1.CrearPlatilloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearPlatilloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal Precio;
        
        public CrearPlatilloRequestBody() {
        }
        
        public CrearPlatilloRequestBody(string Nombre, decimal Precio) {
            this.Nombre = Nombre;
            this.Precio = Precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearPlatilloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearPlatilloResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.CrearPlatilloResponseBody Body;
        
        public CrearPlatilloResponse() {
        }
        
        public CrearPlatilloResponse(Vistas.ServiceReference1.CrearPlatilloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CrearPlatilloResponseBody {
        
        public CrearPlatilloResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTablaPlatilloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTablaPlatillo", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.DevolverTablaPlatilloRequestBody Body;
        
        public DevolverTablaPlatilloRequest() {
        }
        
        public DevolverTablaPlatilloRequest(Vistas.ServiceReference1.DevolverTablaPlatilloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverTablaPlatilloRequestBody {
        
        public DevolverTablaPlatilloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTablaPlatilloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTablaPlatilloResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.DevolverTablaPlatilloResponseBody Body;
        
        public DevolverTablaPlatilloResponse() {
        }
        
        public DevolverTablaPlatilloResponse(Vistas.ServiceReference1.DevolverTablaPlatilloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverTablaPlatilloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vistas.ServiceReference1.ModeloPlatillo[] DevolverTablaPlatilloResult;
        
        public DevolverTablaPlatilloResponseBody() {
        }
        
        public DevolverTablaPlatilloResponseBody(Vistas.ServiceReference1.ModeloPlatillo[] DevolverTablaPlatilloResult) {
            this.DevolverTablaPlatilloResult = DevolverTablaPlatilloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarPlatilloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarPlatillo", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.ModificarPlatilloRequestBody Body;
        
        public ModificarPlatilloRequest() {
        }
        
        public ModificarPlatilloRequest(Vistas.ServiceReference1.ModificarPlatilloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarPlatilloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PkPlatillo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Precio;
        
        public ModificarPlatilloRequestBody() {
        }
        
        public ModificarPlatilloRequestBody(int PkPlatillo, string Nombre, decimal Precio) {
            this.PkPlatillo = PkPlatillo;
            this.Nombre = Nombre;
            this.Precio = Precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarPlatilloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarPlatilloResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.ModificarPlatilloResponseBody Body;
        
        public ModificarPlatilloResponse() {
        }
        
        public ModificarPlatilloResponse(Vistas.ServiceReference1.ModificarPlatilloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarPlatilloResponseBody {
        
        public ModificarPlatilloResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTablaPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTablaPedido", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.DevolverTablaPedidoRequestBody Body;
        
        public DevolverTablaPedidoRequest() {
        }
        
        public DevolverTablaPedidoRequest(Vistas.ServiceReference1.DevolverTablaPedidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverTablaPedidoRequestBody {
        
        public DevolverTablaPedidoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTablaPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTablaPedidoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vistas.ServiceReference1.DevolverTablaPedidoResponseBody Body;
        
        public DevolverTablaPedidoResponse() {
        }
        
        public DevolverTablaPedidoResponse(Vistas.ServiceReference1.DevolverTablaPedidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverTablaPedidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Vistas.ServiceReference1.ModeloPedido[] DevolverTablaPedidoResult;
        
        public DevolverTablaPedidoResponseBody() {
        }
        
        public DevolverTablaPedidoResponseBody(Vistas.ServiceReference1.ModeloPedido[] DevolverTablaPedidoResult) {
            this.DevolverTablaPedidoResult = DevolverTablaPedidoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Vistas.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Vistas.ServiceReference1.WebServiceSoap>, Vistas.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearOrden(int Mesa, System.DateTime Fecha) {
            base.Channel.CrearOrden(Mesa, Fecha);
        }
        
        public System.Threading.Tasks.Task CrearOrdenAsync(int Mesa, System.DateTime Fecha) {
            return base.Channel.CrearOrdenAsync(Mesa, Fecha);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vistas.ServiceReference1.DevolverTablaOrdenResponse Vistas.ServiceReference1.WebServiceSoap.DevolverTablaOrden(Vistas.ServiceReference1.DevolverTablaOrdenRequest request) {
            return base.Channel.DevolverTablaOrden(request);
        }
        
        public Vistas.ServiceReference1.ModeloOrden[] DevolverTablaOrden() {
            Vistas.ServiceReference1.DevolverTablaOrdenRequest inValue = new Vistas.ServiceReference1.DevolverTablaOrdenRequest();
            inValue.Body = new Vistas.ServiceReference1.DevolverTablaOrdenRequestBody();
            Vistas.ServiceReference1.DevolverTablaOrdenResponse retVal = ((Vistas.ServiceReference1.WebServiceSoap)(this)).DevolverTablaOrden(inValue);
            return retVal.Body.DevolverTablaOrdenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaOrdenResponse> Vistas.ServiceReference1.WebServiceSoap.DevolverTablaOrdenAsync(Vistas.ServiceReference1.DevolverTablaOrdenRequest request) {
            return base.Channel.DevolverTablaOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaOrdenResponse> DevolverTablaOrdenAsync() {
            Vistas.ServiceReference1.DevolverTablaOrdenRequest inValue = new Vistas.ServiceReference1.DevolverTablaOrdenRequest();
            inValue.Body = new Vistas.ServiceReference1.DevolverTablaOrdenRequestBody();
            return ((Vistas.ServiceReference1.WebServiceSoap)(this)).DevolverTablaOrdenAsync(inValue);
        }
        
        public void ModificarOrden(int PkOrden, int Mesa, System.DateTime Fecha) {
            base.Channel.ModificarOrden(PkOrden, Mesa, Fecha);
        }
        
        public System.Threading.Tasks.Task ModificarOrdenAsync(int PkOrden, int Mesa, System.DateTime Fecha) {
            return base.Channel.ModificarOrdenAsync(PkOrden, Mesa, Fecha);
        }
        
        public void BorrarOrden(int PkOrden) {
            base.Channel.BorrarOrden(PkOrden);
        }
        
        public System.Threading.Tasks.Task BorrarOrdenAsync(int PkOrden) {
            return base.Channel.BorrarOrdenAsync(PkOrden);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vistas.ServiceReference1.CrearPlatilloResponse Vistas.ServiceReference1.WebServiceSoap.CrearPlatillo(Vistas.ServiceReference1.CrearPlatilloRequest request) {
            return base.Channel.CrearPlatillo(request);
        }
        
        public void CrearPlatillo(string Nombre, decimal Precio) {
            Vistas.ServiceReference1.CrearPlatilloRequest inValue = new Vistas.ServiceReference1.CrearPlatilloRequest();
            inValue.Body = new Vistas.ServiceReference1.CrearPlatilloRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Precio = Precio;
            Vistas.ServiceReference1.CrearPlatilloResponse retVal = ((Vistas.ServiceReference1.WebServiceSoap)(this)).CrearPlatillo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.CrearPlatilloResponse> Vistas.ServiceReference1.WebServiceSoap.CrearPlatilloAsync(Vistas.ServiceReference1.CrearPlatilloRequest request) {
            return base.Channel.CrearPlatilloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vistas.ServiceReference1.CrearPlatilloResponse> CrearPlatilloAsync(string Nombre, decimal Precio) {
            Vistas.ServiceReference1.CrearPlatilloRequest inValue = new Vistas.ServiceReference1.CrearPlatilloRequest();
            inValue.Body = new Vistas.ServiceReference1.CrearPlatilloRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Precio = Precio;
            return ((Vistas.ServiceReference1.WebServiceSoap)(this)).CrearPlatilloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vistas.ServiceReference1.DevolverTablaPlatilloResponse Vistas.ServiceReference1.WebServiceSoap.DevolverTablaPlatillo(Vistas.ServiceReference1.DevolverTablaPlatilloRequest request) {
            return base.Channel.DevolverTablaPlatillo(request);
        }
        
        public Vistas.ServiceReference1.ModeloPlatillo[] DevolverTablaPlatillo() {
            Vistas.ServiceReference1.DevolverTablaPlatilloRequest inValue = new Vistas.ServiceReference1.DevolverTablaPlatilloRequest();
            inValue.Body = new Vistas.ServiceReference1.DevolverTablaPlatilloRequestBody();
            Vistas.ServiceReference1.DevolverTablaPlatilloResponse retVal = ((Vistas.ServiceReference1.WebServiceSoap)(this)).DevolverTablaPlatillo(inValue);
            return retVal.Body.DevolverTablaPlatilloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaPlatilloResponse> Vistas.ServiceReference1.WebServiceSoap.DevolverTablaPlatilloAsync(Vistas.ServiceReference1.DevolverTablaPlatilloRequest request) {
            return base.Channel.DevolverTablaPlatilloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaPlatilloResponse> DevolverTablaPlatilloAsync() {
            Vistas.ServiceReference1.DevolverTablaPlatilloRequest inValue = new Vistas.ServiceReference1.DevolverTablaPlatilloRequest();
            inValue.Body = new Vistas.ServiceReference1.DevolverTablaPlatilloRequestBody();
            return ((Vistas.ServiceReference1.WebServiceSoap)(this)).DevolverTablaPlatilloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vistas.ServiceReference1.ModificarPlatilloResponse Vistas.ServiceReference1.WebServiceSoap.ModificarPlatillo(Vistas.ServiceReference1.ModificarPlatilloRequest request) {
            return base.Channel.ModificarPlatillo(request);
        }
        
        public void ModificarPlatillo(int PkPlatillo, string Nombre, decimal Precio) {
            Vistas.ServiceReference1.ModificarPlatilloRequest inValue = new Vistas.ServiceReference1.ModificarPlatilloRequest();
            inValue.Body = new Vistas.ServiceReference1.ModificarPlatilloRequestBody();
            inValue.Body.PkPlatillo = PkPlatillo;
            inValue.Body.Nombre = Nombre;
            inValue.Body.Precio = Precio;
            Vistas.ServiceReference1.ModificarPlatilloResponse retVal = ((Vistas.ServiceReference1.WebServiceSoap)(this)).ModificarPlatillo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.ModificarPlatilloResponse> Vistas.ServiceReference1.WebServiceSoap.ModificarPlatilloAsync(Vistas.ServiceReference1.ModificarPlatilloRequest request) {
            return base.Channel.ModificarPlatilloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vistas.ServiceReference1.ModificarPlatilloResponse> ModificarPlatilloAsync(int PkPlatillo, string Nombre, decimal Precio) {
            Vistas.ServiceReference1.ModificarPlatilloRequest inValue = new Vistas.ServiceReference1.ModificarPlatilloRequest();
            inValue.Body = new Vistas.ServiceReference1.ModificarPlatilloRequestBody();
            inValue.Body.PkPlatillo = PkPlatillo;
            inValue.Body.Nombre = Nombre;
            inValue.Body.Precio = Precio;
            return ((Vistas.ServiceReference1.WebServiceSoap)(this)).ModificarPlatilloAsync(inValue);
        }
        
        public void BorrarPlatillo(int PkPlatillo) {
            base.Channel.BorrarPlatillo(PkPlatillo);
        }
        
        public System.Threading.Tasks.Task BorrarPlatilloAsync(int PkPlatillo) {
            return base.Channel.BorrarPlatilloAsync(PkPlatillo);
        }
        
        public void CrearPedido(int Platillo, int Orden) {
            base.Channel.CrearPedido(Platillo, Orden);
        }
        
        public System.Threading.Tasks.Task CrearPedidoAsync(int Platillo, int Orden) {
            return base.Channel.CrearPedidoAsync(Platillo, Orden);
        }
        
        public void ModificarPedido(int PkPedido, int Platillo, int Orden) {
            base.Channel.ModificarPedido(PkPedido, Platillo, Orden);
        }
        
        public System.Threading.Tasks.Task ModificarPedidoAsync(int PkPedido, int Platillo, int Orden) {
            return base.Channel.ModificarPedidoAsync(PkPedido, Platillo, Orden);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vistas.ServiceReference1.DevolverTablaPedidoResponse Vistas.ServiceReference1.WebServiceSoap.DevolverTablaPedido(Vistas.ServiceReference1.DevolverTablaPedidoRequest request) {
            return base.Channel.DevolverTablaPedido(request);
        }
        
        public Vistas.ServiceReference1.ModeloPedido[] DevolverTablaPedido() {
            Vistas.ServiceReference1.DevolverTablaPedidoRequest inValue = new Vistas.ServiceReference1.DevolverTablaPedidoRequest();
            inValue.Body = new Vistas.ServiceReference1.DevolverTablaPedidoRequestBody();
            Vistas.ServiceReference1.DevolverTablaPedidoResponse retVal = ((Vistas.ServiceReference1.WebServiceSoap)(this)).DevolverTablaPedido(inValue);
            return retVal.Body.DevolverTablaPedidoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaPedidoResponse> Vistas.ServiceReference1.WebServiceSoap.DevolverTablaPedidoAsync(Vistas.ServiceReference1.DevolverTablaPedidoRequest request) {
            return base.Channel.DevolverTablaPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vistas.ServiceReference1.DevolverTablaPedidoResponse> DevolverTablaPedidoAsync() {
            Vistas.ServiceReference1.DevolverTablaPedidoRequest inValue = new Vistas.ServiceReference1.DevolverTablaPedidoRequest();
            inValue.Body = new Vistas.ServiceReference1.DevolverTablaPedidoRequestBody();
            return ((Vistas.ServiceReference1.WebServiceSoap)(this)).DevolverTablaPedidoAsync(inValue);
        }
        
        public void BorrarPedido(int PkPedido) {
            base.Channel.BorrarPedido(PkPedido);
        }
        
        public System.Threading.Tasks.Task BorrarPedidoAsync(int PkPedido) {
            return base.Channel.BorrarPedidoAsync(PkPedido);
        }
    }
}
